services:
  - type: web
    name: Patent Miner
    env: docker
    repo: https://bitbucket.org/micahread/patent-miner.git
    branch: main
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PATENTSVIEW_API_KEY
        sync: false
    autoDeploy: true
    