services:
  - type: web
    name: Patent Miner
    env: docker
    repo: https://github.com/P5YC0DR3AM3R/Patent-Miner.git
    branch: main
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PATENTSVIEW_API_KEY
        sync: false
    autoDeploy: true
    